/* auto-generated by NAPI-RS */
/* eslint-disable */

export interface RunResult {
  changes: number
}

export declare class Database {
  /**
   * Open a database. Returns a Promise that resolves to a Database instance.
   *
   * Accepts:
   * - `:memory:` or empty string for in-memory database
   * - `memory://` for in-memory database
   * - `file:///path/to/db` for file-based database
   * - Bare path like `./mydb` for file-based database
   */
  static open(path: string): Promise<Database>
  /**
   * Execute a DDL/DML statement. Returns Promise<{ changes: number }>.
   *
   * @param sql - SQL statement
   * @param params - Optional: Array for positional ($1, $2) or Object for named (:key)
   */
  execute(sql: string, params?: any[] | Record<string, any>): Promise<RunResult>
  /**
   * Execute one or more SQL statements separated by semicolons.
   * Returns Promise<void>.
   */
  exec(sql: string): Promise<void>
  /**
   * Query rows. Returns Promise<Array<Object>>.
   *
   * Each row is an object with column names as keys.
   */
  query(sql: string, params?: any[] | Record<string, any>): Promise<Record<string, any>[]>
  /** Query a single row. Returns Promise<Object | null>. */
  queryOne(sql: string, params?: any[] | Record<string, any>): Promise<Record<string, any> | null>
  /**
   * Query rows in raw format. Returns Promise<{ columns: string[], rows: any[][] }>.
   *
   * Faster than query() — skips per-row object creation.
   */
  queryRaw(sql: string, params?: any[] | Record<string, any>): Promise<{ columns: string[], rows: any[][] }>
  /**
   * Execute a DML statement synchronously. Returns { changes: number }.
   *
   * Faster than execute() for simple operations — no async overhead.
   * Blocks the event loop, so use for fast operations only.
   */
  executeSync(sql: string, params?: any[] | Record<string, any>): RunResult
  /**
   * Query rows synchronously. Returns Array<Object>.
   * Uses direct V8 bulk object creation — bypasses NAPI per-property overhead.
   */
  querySync(sql: string, params?: any[] | Record<string, any>): Record<string, any>[]
  /**
   * Query a single row synchronously. Returns Object | null.
   * Uses direct V8 bulk object creation — optimal hidden class in one call.
   */
  queryOneSync(sql: string, params?: any[] | Record<string, any>): Record<string, any> | null
  /**
   * Query rows in raw format synchronously. Returns { columns: string[], rows: any[][] }.
   * Uses direct V8 bulk array creation — bypasses NAPI per-element overhead.
   */
queryRawSync(sql: string, params?: any[] | Record<string, any>): { columns: string[], rows: any[][] }
/**
 * Execute the same SQL with multiple param sets in a single call.
 * Parses SQL once, auto-wraps in a transaction: begin, execute all, commit.
 * Returns { changes: total_rows_affected }.
 */
executeBatchSync(sql: string, paramsArray: any[][]): RunResult
/** Execute one or more SQL statements synchronously. */
execSync(sql: string): void
/** Create a prepared statement (synchronous — parses and caches the plan). */
prepare(sql: string): JsPreparedStatement
/** Begin a transaction. Returns Promise<Transaction>. */
begin(): Promise<Transaction>
/** Begin a transaction synchronously. Returns Transaction. */
beginSync(): Transaction
/** Close the database. Returns Promise<void>. */
close(): Promise<void>
}
export type JsDatabase = Database

export declare class PreparedStatement {
  /** Execute the statement (DML). Returns Promise<{ changes: number }>. */
  execute(params?: any[] | Record<string, any>): Promise<RunResult>
  /** Query rows. Returns Promise<Array<Object>>. */
  query(params?: any[] | Record<string, any>): Promise<Record<string, any>[]>
  /** Query single row. Returns Promise<Object | null>. */
  queryOne(params?: any[] | Record<string, any>): Promise<Record<string, any> | null>
  /** Query rows in raw format. Returns Promise<{ columns: string[], rows: any[][] }>. */
  queryRaw(params?: any[] | Record<string, any>): Promise<{ columns: string[], rows: any[][] }>
  /** Execute synchronously. Returns { changes: number }. */
  executeSync(params?: any[] | Record<string, any>): RunResult
  /**
   * Query rows synchronously. Returns Array<Object>.
   * Uses direct V8 bulk object creation — bypasses NAPI per-property overhead.
   */
  querySync(params?: any[] | Record<string, any>): Record<string, any>[]
  /**
   * Query single row synchronously. Returns Object | null.
   * Uses direct V8 bulk object creation — optimal hidden class in one call.
   */
  queryOneSync(params?: any[] | Record<string, any>): Record<string, any> | null
  /**
   * Query rows in raw format synchronously. Returns { columns: string[], rows: any[][] }.
   * Uses direct V8 bulk array creation — bypasses NAPI per-element overhead.
   */
queryRawSync(params?: any[] | Record<string, any>): { columns: string[], rows: any[][] }
/**
 * Execute the prepared SQL with multiple param sets in a single call.
 * Uses pre-cached AST, auto-wraps in a transaction: begin, execute all, commit.
 * Returns { changes: total_rows_affected }.
 */
executeBatchSync(paramsArray: any[][]): RunResult
/** Get the SQL text of this prepared statement. */
get sql(): string
}
export type JsPreparedStatement = PreparedStatement

export declare class Transaction {
  /**
   * Execute a DML statement within the transaction.
   * Returns Promise<{ changes: number }>.
   */
  execute(sql: string, params?: any[] | Record<string, any>): Promise<RunResult>
  /**
   * Query rows within the transaction.
   * Returns Promise<Array<Object>>.
   */
  query(sql: string, params?: any[] | Record<string, any>): Promise<Record<string, any>[]>
  /**
   * Query a single row within the transaction.
   * Returns Promise<Object | null>.
   */
  queryOne(sql: string, params?: any[] | Record<string, any>): Promise<Record<string, any> | null>
  /**
   * Query rows in raw format within the transaction.
   * Returns Promise<{ columns: string[], rows: any[][] }>.
   */
  queryRaw(sql: string, params?: any[] | Record<string, any>): Promise<{ columns: string[], rows: any[][] }>
  /** Commit the transaction. Returns Promise<void>. */
  commit(): Promise<void>
  /** Rollback the transaction. Returns Promise<void>. */
  rollback(): Promise<void>
  /** Execute a DML statement synchronously. Returns { changes: number }. */
  executeSync(sql: string, params?: any[] | Record<string, any>): RunResult
  /**
   * Query rows synchronously. Returns Array<Object>.
   * Uses direct V8 bulk object creation — bypasses NAPI per-property overhead.
   */
  querySync(sql: string, params?: any[] | Record<string, any>): Record<string, any>[]
  /**
   * Query a single row synchronously. Returns Object | null.
   * Uses direct V8 bulk object creation — optimal hidden class in one call.
   */
  queryOneSync(sql: string, params?: any[] | Record<string, any>): Record<string, any> | null
  /**
   * Query rows in raw format synchronously. Returns { columns: string[], rows: any[][] }.
   * Uses direct V8 bulk array creation — bypasses NAPI per-element overhead.
   */
queryRawSync(sql: string, params?: any[] | Record<string, any>): { columns: string[], rows: any[][] }
/** Commit the transaction synchronously. */
commitSync(): void
/**
 * Execute the same SQL with multiple param sets in a single call.
 * Parses SQL once, locks the transaction once — eliminates per-call overhead.
 * Returns { changes: total_rows_affected }.
 */
executeBatchSync(sql: string, paramsArray: any[][]): RunResult
/** Rollback the transaction synchronously. */
rollbackSync(): void
}
export type JsTransaction = Transaction
