// Copyright 2025 Stoolap Contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Patch the NAPI-RS generated index.d.ts to add custom type definitions.
// NAPI-RS auto-generates the .d.ts but doesn't define types referenced via ts_return_type.

import { readFileSync, writeFileSync } from 'node:fs';

const DTS_PATH = 'index.d.ts';
const HEADER = `/* eslint-disable */

export interface RunResult {
  changes: number
}

`;

let content = readFileSync(DTS_PATH, 'utf8');

// Remove the NAPI-RS auto-generated header (if present)
content = content.replace(/^\/\* auto-generated by NAPI-RS \*\/\n/, '');
content = content.replace(/^\/\* eslint-disable \*\/\n/, '');

// Prepend our header with RunResult type
content = '/* auto-generated by NAPI-RS */\n' + HEADER + content;

writeFileSync(DTS_PATH, content);
